In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [ ]:
df= pd.read_csv('homeprices.csv')
df.head(2)

In [ ]:
df[df.isna().any(axis=1)]

In [ ]:
df.bedrooms.median()

In [39]:
df.bedrooms=df.bedrooms.fillna(df.bedrooms.median())
df.isna().sum()
df.columns

Index(['area', 'bedrooms', 'age', 'price'], dtype='object')

In [41]:
model=linear_model.LinearRegression()
model.fit(df[['area', 'bedrooms', 'age']],df.price)

LinearRegression()

In [42]:
model.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [43]:
model.intercept_

221323.00186540384

In [44]:
model.predict([[3000,3,40]])

array([498408.25158031])

In [45]:
model.predict([[2500,4,5]])

array([578876.03748933])